#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/_Navbar.cshtml")]
    public partial class _Areas_Admin_Views_Index__Navbar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index__Navbar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
  
    var user = ViewBag.User as IUser ?? User.Identity as IUser;
    var uid = 0;
    var roleNames = "";
    if (user != null)
    {
        uid = user.ID;
        roleNames = user.Roles == null ? "" : user.Roles.Join();
    }
    var cfg = ViewBag.Config as SysConfig;
    var name = cfg == null ? "" : cfg.DisplayName;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- #section:basics/navbar.layout -->\r\n<div");

WriteLiteral(" id=\"navbar\"");

WriteLiteral(" class=\"navbar navbar-default\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        try { ace.settings.check(\'navbar\', \'fixed\') } catch (e) { }\r\n    </scr" +
"ipt>\r\n\r\n    <div");

WriteLiteral(" class=\"navbar-container\"");

WriteLiteral(" id=\"navbar-container\"");

WriteLiteral(">\r\n        <!-- #section:basics/sidebar.mobile.toggle -->\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle menu-toggler pull-left\"");

WriteLiteral(" id=\"menu-toggler\"");

WriteLiteral(" data-target=\"#sidebar\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle sidebar</span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n        </button>\r\n\r\n        <!-- /section:basics/sidebar.mobile.toggle" +
" -->\r\n        <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n            <!-- #section:basics/navbar.layout.brand -->\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1203), Tuple.Create("\"", 1223)
            
            #line 33 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
, Tuple.Create(Tuple.Create("", 1210), Tuple.Create<System.Object, System.Int32>(ViewBag.Main
            
            #line default
            #line hidden
, 1210), false)
);

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n                <small>\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
               Write(name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </small>\r\n            </a>\r\n        </div>\r\n\r\n        <!-- #sec" +
"tion:basics/navbar.dropdown -->\r\n        <div");

WriteLiteral(" class=\"navbar-buttons navbar-header pull-right\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav ace-nav\"");

WriteLiteral(">\r\n                <!-- #section:basics/navbar.user_menu -->\r\n                <li" +
"");

WriteLiteral(" class=\"light-blue\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1690), Tuple.Create("\"", 1719)
, Tuple.Create(Tuple.Create("", 1697), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/User/Info/")
, 1697), false)
            
            #line 45 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
, Tuple.Create(Tuple.Create("", 1715), Tuple.Create<System.Object, System.Int32>(uid
            
            #line default
            #line hidden
, 1715), false)
);

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n");

            
            #line 46 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
                         if (user != null && !user.Avatar.IsNullOrEmpty())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <img");

WriteLiteral(" class=\"nav-user-photo\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1919), Tuple.Create("\"", 1945)
            
            #line 48 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
, Tuple.Create(Tuple.Create("", 1925), Tuple.Create<System.Object, System.Int32>(user.GetAvatarUrl()
            
            #line default
            #line hidden
, 1925), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 1946), Tuple.Create("\"", 1957)
            
            #line 48 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
        , Tuple.Create(Tuple.Create("", 1952), Tuple.Create<System.Object, System.Int32>(user
            
            #line default
            #line hidden
, 1952), false)
);

WriteLiteral(" />\r\n");

            
            #line 49 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"user-info\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 52 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
                       Write(user);

            
            #line default
            #line hidden
WriteLiteral(" <br /> [");

            
            #line 52 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
                                     Write(roleNames);

            
            #line default
            #line hidden
WriteLiteral("]\r\n                        </span>\r\n\r\n                        <i");

WriteLiteral(" class=\"ace-icon fa fa-caret-down\"");

WriteLiteral("></i>\r\n                    </a>\r\n\r\n                    <ul");

WriteLiteral(" class=\"user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-care" +
"t dropdown-close\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2461), Tuple.Create("\"", 2470)
, Tuple.Create(Tuple.Create("", 2468), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 2468), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"ace-icon fa fa-cog\"");

WriteLiteral("></i>\r\n                                网站首页\r\n                            </a>\r\n  " +
"                      </li>\r\n\r\n                        ");

WriteLiteral("\r\n\r\n                        <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3181), Tuple.Create("\"", 3210)
, Tuple.Create(Tuple.Create("", 3188), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/User/Info/")
, 3188), false)
            
            #line 77 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
, Tuple.Create(Tuple.Create("", 3206), Tuple.Create<System.Object, System.Int32>(uid
            
            #line default
            #line hidden
, 3206), false)
);

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"ace-icon fa fa-user\"");

WriteLiteral("></i>\r\n                                个人信息\r\n                            </a>\r\n  " +
"                      </li>\r\n\r\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n\r\n                        <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3515), Tuple.Create("\"", 3541)
, Tuple.Create(Tuple.Create("", 3522), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/User/Logout")
, 3522), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"ace-icon fa fa-power-off\"");

WriteLiteral(@"></i>
                                注销
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- /section:basics/navbar.user_menu -->
            </ul>
        </div>

        <!-- /section:basics/navbar.dropdown -->
    </div>
    <!-- /.navbar-container -->
</div>
<!-- /section:basics/navbar.layout -->");

        }
    }
}
#pragma warning restore 1591
