#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 2 "..\..\Areas\Admin\Views\Index\Main.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Admin\Views\Index\Main.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 3 "..\..\Areas\Admin\Views\Index\Main.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\Index\Main.cshtml"
    using System.Runtime.Versioning;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 5 "..\..\Areas\Admin\Views\Index\Main.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 6 "..\..\Areas\Admin\Views\Index\Main.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/Main.cshtml")]
    public partial class _Areas_Admin_Views_Index_Main_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index_Main_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Areas\Admin\Views\Index\Main.cshtml"
  
    Layout = NewLife.Cube.Setting.Current.Layout;

    ViewBag.Title = "服务器信息";

    var asm = Assembly.GetExecutingAssembly();
    var att = asm.GetCustomAttribute<TargetFrameworkAttribute>();
    var ver = att.FrameworkDisplayName ?? att.FrameworkName;
    var req = HttpContext.Current.Request;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                服务器信息\r\n            </th>\r\n        </tr>\r\n    </thead>\r\n    <tb" +
"ody>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                应用系统：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(HttpRuntime.AppDomainAppVirtualPath);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;\r\n");

            
            #line 32 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                 if (this.Has((PermissionFlags)16))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 970), Tuple.Create("\"", 999)
            
            #line 34 "..\..\Areas\Admin\Views\Index\Main.cshtml"
, Tuple.Create(Tuple.Create("", 977), Tuple.Create<System.Object, System.Int32>(Url.Action("Restart")
            
            #line default
            #line hidden
, 977), false)
);

WriteLiteral(" onclick=\"return confirm(\'仅重启ASP.Net应用程序域，而不是操作系统！\\n确认重启？\')\"");

WriteLiteral(">重启应用系统</a>\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                &nbsp;&nbsp;&nbsp;&nbsp;");

            
            #line 36 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                   Write(req.GetRawUrl());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                目录：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(HttpRuntime.AppDomainAppPath);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                域名地址：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" title=\"SERVER_NAME\"");

WriteLiteral(">");

            
            #line 50 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                     Write(Request.ServerVariables["SERVER_NAME"]);

            
            #line default
            #line hidden
WriteLiteral("</span>，\r\n                <span");

WriteLiteral(" title=\"LOCAl_ADDR\"");

WriteLiteral(">");

            
            #line 51 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                    Write(Request.ServerVariables["LOCAl_ADDR"]);

            
            #line default
            #line hidden
WriteLiteral(":");

            
            #line 51 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                                                           Write(Request.ServerVariables["Server_Port"]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                &nbsp;<span");

WriteLiteral(" title=\"REMOTE_HOST\"");

WriteLiteral(">[");

            
            #line 52 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                            Write(Request.ServerVariables["REMOTE_HOST"]);

            
            #line default
            #line hidden
WriteLiteral("]</span>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1807), Tuple.Create("\"", 1843)
            
            #line 53 "..\..\Areas\Admin\Views\Index\Main.cshtml"
, Tuple.Create(Tuple.Create("", 1814), Tuple.Create<System.Object, System.Int32>(Url.Action("Main/ServerVar")
            
            #line default
            #line hidden
, 1814), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" title=\"点击打开服务器变量列表\"");

WriteLiteral(">服务器变量列表</a>\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                计算机用户：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 59 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(Environment.UserName);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 59 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                 Write(Environment.MachineName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                应用程序域：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 67 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(AppDomain.CurrentDomain.FriendlyName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2310), Tuple.Create("\"", 2345)
            
            #line 68 "..\..\Areas\Admin\Views\Index\Main.cshtml"
, Tuple.Create(Tuple.Create("", 2317), Tuple.Create<System.Object, System.Int32>(Url.Action("Main/Assembly")
            
            #line default
            #line hidden
, 2317), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" title=\"点击打开进程程序集列表\"");

WriteLiteral(">程序集列表</a>\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                .Net 版本：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 74 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(Environment.Version);

            
            #line default
            #line hidden
WriteLiteral(" &nbsp;");

            
            #line 74 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                      Write(ver);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                操作系统：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 82 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(Runtime.OSName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                Web服务器：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 88 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(ViewBag.WebServerName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                处理器：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 96 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(Environment.ProcessorCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n                核心\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                时间：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(" title=\"这里使用了服务器默认的时间格式！后面是开机时间。\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 103 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(DateTime.Now);

            
            #line default
            #line hidden
WriteLiteral("，开机");

            
            #line 103 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                            Write(new TimeSpan(0, 0, 0, 0, Environment.TickCount));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n");

            
            #line 107 "..\..\Areas\Admin\Views\Index\Main.cshtml"
            
            
            #line default
            #line hidden
            
            #line 107 "..\..\Areas\Admin\Views\Index\Main.cshtml"
               var process = Process.GetCurrentProcess();
            
            #line default
            #line hidden
WriteLiteral("\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                内存：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n                物理内存：");

            
            #line 112 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                 Write(Runtime.AvailableMemory.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("M / ");

            
            #line 112 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                                              Write(Runtime.PhysicalMemory.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("M\r\n                工作集: ");

            
            #line 113 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                 Write((process.WorkingSet64 / 1024 / 1024).ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("M\r\n                提交: ");

            
            #line 114 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                Write((process.PrivateMemorySize64 / 1024 / 1024).ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("M\r\n                GC: ");

            
            #line 115 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                Write((GC.GetTotalMemory(false) / 1024 / 1024).ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("M\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3959), Tuple.Create("\"", 4000)
            
            #line 116 "..\..\Areas\Admin\Views\Index\Main.cshtml"
, Tuple.Create(Tuple.Create("", 3966), Tuple.Create<System.Object, System.Int32>(Url.Action("Main/ProcessModules")
            
            #line default
            #line hidden
, 3966), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" title=\"点击打开进程模块列表\"");

WriteLiteral(">模块列表</a>\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                进程时间：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 122 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(process.TotalProcessorTime.TotalSeconds.ToString("N2"));

            
            #line default
            #line hidden
WriteLiteral("秒 启动于 ");

            
            #line 122 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                                                        Write(process.StartTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                Session：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 130 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(Session.Contents.Count);

            
            #line default
            #line hidden
WriteLiteral(" 个，");

            
            #line 130 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                     Write(Session.Timeout);

            
            #line default
            #line hidden
WriteLiteral(" 分钟，SessionID：");

            
            #line 130 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                                                                   Write(Session.Contents.SessionID);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4558), Tuple.Create("\"", 4592)
            
            #line 131 "..\..\Areas\Admin\Views\Index\Main.cshtml"
, Tuple.Create(Tuple.Create("", 4565), Tuple.Create<System.Object, System.Int32>(Url.Action("Main/Session")
            
            #line default
            #line hidden
, 4565), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" title=\"点击打开Session列表\"");

WriteLiteral(">Session列表</a>\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n                Cache：\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 137 "..\..\Areas\Admin\Views\Index\Main.cshtml"
           Write(Cache.Count);

            
            #line default
            #line hidden
WriteLiteral(" 个，可用：");

            
            #line 137 "..\..\Areas\Admin\Views\Index\Main.cshtml"
                              Write((Cache.EffectivePrivateBytesLimit / 1024).ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("KB\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4887), Tuple.Create("\"", 4919)
            
            #line 138 "..\..\Areas\Admin\Views\Index\Main.cshtml"
, Tuple.Create(Tuple.Create("", 4894), Tuple.Create<System.Object, System.Int32>(Url.Action("Main/Cache")
            
            #line default
            #line hidden
, 4894), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" title=\"点击打开Cache列表\"");

WriteLiteral(">Cache列表</a>\r\n            </td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th>名称</th>\r\n            <th>标题</th>\r\n " +
"           <th>文件版本</th>\r\n            <th>内部版本</th>\r\n            <th>编译时间</th>\r\n" +
"            <th>描述</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 155 "..\..\Areas\Admin\Views\Index\Main.cshtml"
        
            
            #line default
            #line hidden
            
            #line 155 "..\..\Areas\Admin\Views\Index\Main.cshtml"
         foreach (AssemblyX item in ViewBag.MyAsms)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>");

            
            #line 158 "..\..\Areas\Admin\Views\Index\Main.cshtml"
               Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 159 "..\..\Areas\Admin\Views\Index\Main.cshtml"
               Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 160 "..\..\Areas\Admin\Views\Index\Main.cshtml"
               Write(item.FileVersion);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 161 "..\..\Areas\Admin\Views\Index\Main.cshtml"
               Write(item.Version);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 162 "..\..\Areas\Admin\Views\Index\Main.cshtml"
               Write(item.Compile.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 163 "..\..\Areas\Admin\Views\Index\Main.cshtml"
               Write(item.Description);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");

            
            #line 165 "..\..\Areas\Admin\Views\Index\Main.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
