#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Ace_Layout.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Ace_Layout.cshtml")]
    public partial class _Views_Shared__Ace_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Ace_Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_Ace_Layout.cshtml"
  
    var p = Context.Request.CurrentExecutionFilePath;
    var ss = p.Split("/");
    if (ss != null && ss.Length > 1 && ss[ss.Length - 1].IsInt())
    {
        p = p.Substring(0, p.LastIndexOf("/"));
    }
    var menu = ManageProvider.Menu.Root.FindByPath(p);

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh-CN\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n\r\n    <title>");

            
            #line 19 "..\..\Views\Shared\_Ace_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 19 "..\..\Views\Shared\_Ace_Layout.cshtml"
                       Write(SysConfig.Current.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 641), Tuple.Create("\"", 661)
, Tuple.Create(Tuple.Create("", 648), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 648), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n\r\n    <!-- 页面内联样式 -->\r\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!-- 文本字体 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 821), Tuple.Create("\"", 863)
, Tuple.Create(Tuple.Create("", 828), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/css/ace-fonts.min.css")
, 828), false)
);

WriteLiteral(" />\r\n    <!-- ace 样式 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 916), Tuple.Create("\"", 952)
, Tuple.Create(Tuple.Create("", 923), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/css/ace.min.css")
, 923), false)
);

WriteLiteral(" class=\"ace-main-stylesheet\"");

WriteLiteral(" id=\"main-ace-style\"");

WriteLiteral(" />\r\n\r\n    <!--[if lte IE 9]>\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1062), Tuple.Create("\"", 1104)
, Tuple.Create(Tuple.Create("", 1069), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/css/ace-part2.min.css")
, 1069), false)
);

WriteLiteral(" class=\"ace-main-stylesheet\"");

WriteLiteral(" />\r\n    <![endif]-->\r\n    <!--[if lte IE 9]>\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1210), Tuple.Create("\"", 1249)
, Tuple.Create(Tuple.Create("", 1217), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/css/ace-ie.min.css")
, 1217), false)
);

WriteLiteral(" />\r\n    <![endif]-->\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1301), Tuple.Create("\"", 1365)
, Tuple.Create(Tuple.Create("", 1308), Tuple.Create<System.Object, System.Int32>(Href("~/Content/DateTimePicker/bootstrap-datetimepicker.min.css")
, 1308), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n    ");

WriteLiteral("\r\n\r\n    <!-- 最后引入基本样式 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1545), Tuple.Create("\"", 1593)
, Tuple.Create(Tuple.Create("", 1552), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/bootstrap.min.css")
, 1552), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1625), Tuple.Create("\"", 1676)
, Tuple.Create(Tuple.Create("", 1632), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/font-awesome.min.css")
, 1632), false)
);

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1710), Tuple.Create("\"", 1764)
, Tuple.Create(Tuple.Create("", 1717), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/bootstrap-theme.min.css")
, 1717), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1812), Tuple.Create("\"", 1871)
, Tuple.Create(Tuple.Create("", 1819), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/bootstrap-responsive.min.css")
, 1819), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n    <!-- JQuery作为一等公民，页面内部随时可能使用 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1944), Tuple.Create("\"", 1982)
, Tuple.Create(Tuple.Create("", 1950), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-2.1.3.min.js")
, 1950), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"ace-icon fa fa-home home-icon\"");

WriteLiteral("></i>\r\n");

            
            #line 55 "..\..\Views\Shared\_Ace_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\_Ace_Layout.cshtml"
             if (menu != null)
            {
                foreach (IMenu item in menu.AllParents)
                {
                    if (item.ID != 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2346), Tuple.Create("\"", 2397)
            
            #line 61 "..\..\Views\Shared\_Ace_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2353), Tuple.Create<System.Object, System.Int32>(item.Url!=null? Url.Content(item.Url):"#"
            
            #line default
            #line hidden
, 2353), false)
);

WriteLiteral(" class=\"h4\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\Shared\_Ace_Layout.cshtml"
                                                                         Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("            ");

WriteLiteral("&nbsp;/&nbsp;");

WriteLiteral("\r\n");

            
            #line 63 "..\..\Views\Shared\_Ace_Layout.cshtml"
                    }
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2544), Tuple.Create("\"", 2571)
            
            #line 66 "..\..\Views\Shared\_Ace_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2551), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 2551), false)
);

WriteLiteral(" class=\"h4\"");

WriteLiteral("><strong>");

            
            #line 66 "..\..\Views\Shared\_Ace_Layout.cshtml"
                                                          Write(menu != null ? menu.DisplayName : ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</strong></a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 70 "..\..\Views\Shared\_Ace_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n    </div>\r\n    <!-- 最早引入基本脚本 -->\r\n    " +
"<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2894), Tuple.Create("\"", 2939)
, Tuple.Create(Tuple.Create("", 2900), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/js/bootstrap.min.js")
, 2900), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n\r\n    <!-- ace 设置 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3127), Tuple.Create("\"", 3160)
, Tuple.Create(Tuple.Create("", 3133), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/js/ace.min.js")
, 3133), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3184), Tuple.Create("\"", 3226)
, Tuple.Create(Tuple.Create("", 3190), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/js/ace-elements.min.js")
, 3190), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3250), Tuple.Create("\"", 3289)
, Tuple.Create(Tuple.Create("", 3256), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/js/ace-extra.min.js")
, 3256), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements" +
" and media queries -->\r\n    <!--[if lte IE 8]>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3430), Tuple.Create("\"", 3465)
, Tuple.Create(Tuple.Create("", 3436), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/html5shiv.min.js")
, 3436), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3489), Tuple.Create("\"", 3522)
, Tuple.Create(Tuple.Create("", 3495), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/respond.min.js")
, 3495), false)
);

WriteLiteral("></script>\r\n    <![endif]-->\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 91 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!--日历控件支持-->\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3751), Tuple.Create("\"", 3813)
, Tuple.Create(Tuple.Create("", 3757), Tuple.Create<System.Object, System.Int32>(Href("~/Content/DateTimePicker/bootstrap-datetimepicker.min.js")
, 3757), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3837), Tuple.Create("\"", 3909)
, Tuple.Create(Tuple.Create("", 3843), Tuple.Create<System.Object, System.Int32>(Href("~/Content/DateTimePicker/locales/bootstrap-datetimepicker.zh-CN.js")
, 3843), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        //$(function () {\r\n        //    // 给所有type=dat" +
"e的input加上事件\r\n        //    var dt = $(\'input[type=date]\');\r\n        //    if (!d" +
"t.data(\'datd-date-format\')) {\r\n        //        dt.data(\'datd-date-format\', \'yy" +
"yy-MM-dd HH:mm:ss\');\r\n        //    }\r\n        //    if (!dt.data(\'click\')) {\r\n " +
"       //        dt.click(function () { WdatePicker({ skin: \'whyGreen\', dateFmt:" +
" dt.data(\'datd-date-format\') }); });\r\n        //    }\r\n        //});\r\n        $(" +
"function () {\r\n            $(\'input[type=date]\').each(function () {\r\n           " +
"     var df = $(this).attr(\'dateformat\');\r\n                if (!df) {\r\n         " +
"           $(this).attr(\'dateformat\', \'yyyy-mm-dd hh:ii:ss\');\r\n                }" +
"\r\n                else {\r\n                    // 把C#标准格式化替换为控件格式\r\n              " +
"      df = df.replace(\'mm\', \'ii\').replace(\'MM\', \'mm\').replace(\'HH\', \'hh\');\r\n    " +
"                $(this).attr(\'dateformat\', df);\r\n                }\r\n            " +
"});\r\n            $(\"[dateformat]\").each(function () {\r\n                $(this).d" +
"atetimepicker({\r\n                    format: $(this).attr(\"dateformat\"),\r\n      " +
"              autoclose: true,\r\n                    language: \"zh-CN\",\r\n        " +
"            forceParse: false,\r\n                    startView: 2,\r\n             " +
"       minView: 2,\r\n                })\r\n                //console.trace($(this))" +
";\r\n            })\r\n            $(\'input[role=number]\').each(function () {\r\n     " +
"           $(this).removeAttr(\'class\');\r\n                $(this).addClass(\'spinb" +
"ox-input form-control text-center\');\r\n                $(this).ace_spinner({ on_s" +
"ides: true, icon_up: \'ace-icon fa fa-plus bigger-110\', icon_down: \'ace-icon fa f" +
"a-minus bigger-110\', btn_up_class: \'btn-success\', btn_down_class: \'btn-danger\' }" +
");\r\n            });\r\n        });\r\n    </script>\r\n\r\n    <!--开关插件-->\r\n    ");

WriteLiteral("\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5955), Tuple.Create("\"", 5999)
, Tuple.Create(Tuple.Create("", 5961), Tuple.Create<System.Object, System.Int32>(Href("~/Content/fuelux/fuelux.spinner.min.js")
, 5961), false)
);

WriteLiteral("></script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
