#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_Form_Item.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_Item.cshtml")]
    public partial class _Views_Shared__Form_Item_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_Item_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_Form_Item.cshtml"
  
    var pair = Model as Pair;
    var entity = pair.First as IEntity;
    var item = pair.Second as FieldItem;

    var bs = this.Bootstrap();

    var isInt = item.Type == typeof(Int32);
    var w = isInt ? 4 : 8;

    var w_md = bs.LabelWidth;
    if (bs.MaxColumn > 1 && item.Type == typeof(String) && item.Length > 100)
    {
        w_md /= 2;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<label");

WriteAttribute("class", Tuple.Create(" class=\"", 443), Tuple.Create("\"", 502)
, Tuple.Create(Tuple.Create("", 451), Tuple.Create("control-label", 451), true)
, Tuple.Create(Tuple.Create(" ", 464), Tuple.Create("col-xs-2", 465), true)
, Tuple.Create(Tuple.Create(" ", 473), Tuple.Create("col-md-", 474), true)
            
            #line 20 "..\..\Views\Shared\_Form_Item.cshtml"
, Tuple.Create(Tuple.Create("", 481), Tuple.Create<System.Object, System.Int32>(w_md
            
            #line default
            #line hidden
, 481), false)
, Tuple.Create(Tuple.Create(" ", 486), Tuple.Create("no-padding-left", 487), true)
);

WriteLiteral(">");

            
            #line 20 "..\..\Views\Shared\_Form_Item.cshtml"
                                                              Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 535), Tuple.Create("\"", 574)
, Tuple.Create(Tuple.Create("", 543), Tuple.Create("input-group", 543), true)
, Tuple.Create(Tuple.Create(" ", 554), Tuple.Create("col-xs-10", 555), true)
, Tuple.Create(Tuple.Create(" ", 564), Tuple.Create("col-sm-", 565), true)
            
            #line 21 "..\..\Views\Shared\_Form_Item.cshtml"
, Tuple.Create(Tuple.Create("", 572), Tuple.Create<System.Object, System.Int32>(w
            
            #line default
            #line hidden
, 572), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\Shared\_Form_Item.cshtml"
Write(Html.ForEditor(item, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <span");

WriteLiteral(" class=\"hidden-xs\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Shared\_Form_Item.cshtml"
                       Write(Html.ForDescription(item));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 24 "..\..\Views\Shared\_Form_Item.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_Form_Item.cshtml"
      
        ModelState st = null;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 27 "..\..\Views\Shared\_Form_Item.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Shared\_Form_Item.cshtml"
     if (ViewData.ModelState.TryGetValue(item.Name, out st) && st != null && st.Errors.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Shared\_Form_Item.cshtml"
       Write(Html.ValidationMessage(item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n");

            
            #line 32 "..\..\Views\Shared\_Form_Item.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
