#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Data_Action.cshtml")]
    public partial class _Views_Shared__List_Data_Action_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Data_Action_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_List_Data_Action.cshtml"
 if (ManageProvider.User.Has(PermissionFlags.Update))
{

            
            #line default
            #line hidden
WriteLiteral("    <i");

WriteLiteral(" class=\"glyphicon glyphicon-edit\"");

WriteLiteral(" style=\"color: blue;\"");

WriteLiteral("></i>\r\n");

            
            #line 4 "..\..\Views\Shared\_List_Data_Action.cshtml"
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\Shared\_List_Data_Action.cshtml"
Write(Html.ActionLink("编辑", "Edit", new { id = @Model }));

            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\Shared\_List_Data_Action.cshtml"
                                                       
}
else if (ManageProvider.User.Has(PermissionFlags.Detail))
{

            
            #line default
            #line hidden
WriteLiteral("    <i");

WriteLiteral(" class=\"glyphicon glyphicon-edit\"");

WriteLiteral(" style=\"color: blue;\"");

WriteLiteral("></i>\r\n");

            
            #line 9 "..\..\Views\Shared\_List_Data_Action.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\_List_Data_Action.cshtml"
Write(Html.ActionLink("查看", "Edit", new { id = @Model }));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\_List_Data_Action.cshtml"
                                                       
}

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\_List_Data_Action.cshtml"
 if (ManageProvider.User.Has(PermissionFlags.Delete))
{

            
            #line default
            #line hidden
WriteLiteral("    <i");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral(" style=\"color: red;\"");

WriteLiteral("></i>\r\n");

            
            #line 14 "..\..\Views\Shared\_List_Data_Action.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Shared\_List_Data_Action.cshtml"
Write(Html.ActionLink("删除", "Delete", new { id = @Model }, new { onclick = "return confirm('确认删除？');" }));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Shared\_List_Data_Action.cshtml"
                                                                                                       
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
