#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_List_Search.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_List_Search.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    
    #line 2 "..\..\Views\Shared\_List_Search.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_List_Search.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Search.cshtml")]
    public partial class _Views_Shared__List_Search_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Search_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_List_Search.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var fi = fact.MasterTime;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Shared\_List_Search.cshtml"
 if (fi != null)
{
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\_List_Search.cshtml"
Write(Html.Partial("_DateRange"));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\_List_Search.cshtml"
                               
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
