#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 1 "..\..\Views\Shared\List.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\List.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/List.cshtml")]
    public partial class _Views_Shared_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\List.cshtml"
  
    Layout = "~/Views/Shared/_Ace_Layout.cshtml";

    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Shared\List.cshtml"
Write(Html.Partial("_List_Toolbar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Views\Shared\List.cshtml"
Write(Html.Partial("_List_Data"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n    <p>\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Shared\List.cshtml"
   Write(Html.Partial("_List_Pager"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n</div>\r\n\r\n<script>\r\n    $(function () {\r\n\r\n        //为所有data-action加上" +
"事件\r\n        $(\'[data-action]\').each(function () {\r\n            $(this).data(\'cli" +
"ck\', this.onclick);\r\n            this.onclick = null;\r\n        });\r\n\r\n        $(" +
"document).on(\'click\', \'[data-action]\', function (e) {\r\n\r\n            var that = " +
"$(this),\r\n                oldClick = that.data(\'click\');\r\n            isAjax = t" +
"hat.data(\'ajax\');\r\n            action = that.data(\'action\');\r\n            if (!!" +
"isAjax) {\r\n                //如果标志为ajax，阻止默认事件，\r\n                this.onclick = n" +
"ull;\r\n                e.stopPropagation();\r\n                e.preventDefault();\r" +
"\n                switch (action) {\r\n                    case \'view\':\r\n          " +
"              break;\r\n                    case \'edit\':\r\n                        " +
"break;\r\n                    case \'delete\':\r\n                        //console.lo" +
"g(\'delete\');\r\n                        confirmDialog(\'确认删除？\', function () {\r\n    " +
"                        $.post(that.attr(\'href\'),\r\n                             " +
" function (data) {\r\n                                  //console.log(data);\r\n\r\n  " +
"                                tips(data.msg, 1, 1000, \'iframe|\'+ data.url); \r\n" +
"                                  \r\n                              }).error(funct" +
"ion (error) {\r\n                                  infoDialog(\'提示\', error || \'删除失败" +
"\', 1);\r\n                              });\r\n                        }); \r\n\r\n     " +
"                   break;\r\n                    case \'add\':\r\n                    " +
"    break;\r\n                }\r\n\r\n                return false;\r\n            } el" +
"se {\r\n\r\n                oldClick && oldClick.call(this);\r\n            }\r\n       " +
" });\r\n    });\r\n\r\n</script>");

        }
    }
}
#pragma warning restore 1591
