#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EntityList/_Toolbar_Adv.cshtml")]
    public partial class _Views_EntityList__Toolbar_Adv_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_EntityList__Toolbar_Adv_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <button");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"btn btn-info btn-sm btn-sm-force dropdown-toggle\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n        高级\r\n        <span");

WriteLiteral(" class=\"ace-icon fa fa-caret-down icon-on-right\"");

WriteLiteral("></span>\r\n    </button>\r\n\r\n    <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-info dropdown-menu-right\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 335), Tuple.Create("\"", 368)
            
            #line 9 "..\..\Views\EntityList\_Toolbar_Adv.cshtml"
, Tuple.Create(Tuple.Create("", 342), Tuple.Create<System.Object, System.Int32>(Url.Action("ExportExcel")
            
            #line default
            #line hidden
, 342), false)
);

WriteLiteral(">导出Excel</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 426), Tuple.Create("\"", 457)
            
            #line 12 "..\..\Views\EntityList\_Toolbar_Adv.cshtml"
, Tuple.Create(Tuple.Create("", 433), Tuple.Create<System.Object, System.Int32>(Url.Action("ExportXml")
            
            #line default
            #line hidden
, 433), false)
);

WriteLiteral(">导出Xml</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 513), Tuple.Create("\"", 544)
            
            #line 15 "..\..\Views\EntityList\_Toolbar_Adv.cshtml"
, Tuple.Create(Tuple.Create("", 520), Tuple.Create<System.Object, System.Int32>(Url.Action("ImportXml")
            
            #line default
            #line hidden
, 520), false)
);

WriteLiteral(">导入Xml</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 600), Tuple.Create("\"", 632)
            
            #line 18 "..\..\Views\EntityList\_Toolbar_Adv.cshtml"
, Tuple.Create(Tuple.Create("", 607), Tuple.Create<System.Object, System.Int32>(Url.Action("ExportJson")
            
            #line default
            #line hidden
, 607), false)
);

WriteLiteral(">导出Json</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 689), Tuple.Create("\"", 721)
            
            #line 21 "..\..\Views\EntityList\_Toolbar_Adv.cshtml"
, Tuple.Create(Tuple.Create("", 696), Tuple.Create<System.Object, System.Int32>(Url.Action("ImportJson")
            
            #line default
            #line hidden
, 696), false)
);

WriteLiteral(">导入Json</a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 813), Tuple.Create("\"", 840)
            
            #line 25 "..\..\Views\EntityList\_Toolbar_Adv.cshtml"
, Tuple.Create(Tuple.Create("", 820), Tuple.Create<System.Object, System.Int32>(Url.Action("Clear")
            
            #line default
            #line hidden
, 820), false)
);

WriteLiteral(" onclick=\"return confirm(\'该操作将删除数据表所有数据并不可恢复！\\n确认清空？\');\"");

WriteLiteral(">清空数据表</a>\r\n        </li>\r\n    </ul>\r\n</div><!-- /.btn-group -->");

        }
    }
}
#pragma warning restore 1591
