#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Log/_List_Search.cshtml")]
    public partial class _Areas_Admin_Views_Log__List_Search_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Log__List_Search_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"category\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">类别：</label>\r\n");

WriteLiteral("    ");

            
            #line 3 "..\..\Areas\Admin\Views\Log\_List_Search.cshtml"
Write(Html.ForDropDownList("category", Log.FindAllCategoryName(), Request["category"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"userid\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">用户：</label>\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Areas\Admin\Views\Log\_List_Search.cshtml"
Write(Html.ForDropDownList("userid", UserX.FindAllWithCache(), "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"dtStart\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">时间：</label>\r\n    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\r\n        <input");

WriteLiteral(" name=\"dtStart\"");

WriteLiteral(" id=\"dtStart\"");

WriteAttribute("value", Tuple.Create(" value=\"", 600), Tuple.Create("\"", 627)
            
            #line 13 "..\..\Areas\Admin\Views\Log\_List_Search.cshtml"
, Tuple.Create(Tuple.Create("", 608), Tuple.Create<System.Object, System.Int32>(Request["dtStart"]
            
            #line default
            #line hidden
, 608), false)
);

WriteLiteral(" dateformat=\"yyyy-MM-dd\"");

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"dtEnd\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">至</label>\r\n    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\r\n        <input");

WriteLiteral(" name=\"dtEnd\"");

WriteLiteral(" id=\"dtEnd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 942), Tuple.Create("\"", 967)
            
            #line 20 "..\..\Areas\Admin\Views\Log\_List_Search.cshtml"
, Tuple.Create(Tuple.Create("", 950), Tuple.Create<System.Object, System.Int32>(Request["dtEnd"]
            
            #line default
            #line hidden
, 950), false)
);

WriteLiteral(" dateformat=\"yyyy-MM-dd\"");

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
