#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_Login_Login.cshtml")]
    public partial class _Areas_Admin_Views_User__Login_Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__Login_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
  
    var set = NewLife.Cube.Setting.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(" id=\"Login\"");

WriteLiteral(">\r\n    <!-- Logo-->\r\n    <div");

WriteLiteral(" class=\"row text-center\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"glyphicon glyphicon-cloud login-logo center-block\"");

WriteLiteral("></i>\r\n    </div>\r\n    <!-- 登录-->\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
     using (Html.BeginForm("Login", "User", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "cube-login" }))
    {
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
   Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"heading text-primary\"");

WriteLiteral(">用户登录</span>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"username\"");

WriteLiteral(" name=\"username\"");

WriteLiteral(" placeholder=\"用户名或电子邮件\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral("></i>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"password\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(" placeholder=\"密　码\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-lock\"");

WriteLiteral("></i>\r\n            ");

WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"main-checkbox\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" id=\"remember\"");

WriteLiteral(" name=\"remember\"");

WriteLiteral(" />\r\n                    <label");

WriteLiteral(" for=\"remember\"");

WriteLiteral("></label>\r\n                </div>\r\n                <span");

WriteLiteral(" class=\"text text-primary\"");

WriteLiteral(">记住我</span>\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">登录</button>\r\n            </div>\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"

    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 33 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
     if (set.AllowRegister || set.AllowForgot)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"toolbar clearfix text-center\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding-top:30px;\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
                
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
                 if (set.AllowForgot)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" href=\"#Forgot\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-info-sign\"");

WriteLiteral("></i>\r\n                        忘记密码？\r\n                    </a>\r\n");

            
            #line 43 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 45 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
                 if (set.AllowRegister)
                {


            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" href=\"#Register\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">                        \r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-menu-right\"");

WriteLiteral("></i>\r\n                        我要注册\r\n                    </a>\r\n");

            
            #line 52 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n");

            
            #line 56 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 58 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
    
            
            #line default
            #line hidden
            
            #line 58 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
     if (!set.LoginTip.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <h4");

WriteLiteral(" class=\"header blue lighter bigger\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"ace-icon fa fa-coffee green\"");

WriteLiteral("></i>\r\n\r\n        </h4>\r\n");

            
            #line 64 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"space-6\"");

WriteLiteral("></div>\r\n");

            
            #line 66 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <nav");

WriteLiteral(" class=\"navbar navbar-fixed-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"alert alert-warning alert-dismissible text-center\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(" style=\"margin-bottom:0px;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n");

WriteLiteral("                ");

            
            #line 70 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
           Write(Html.Raw(set.LoginTip));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </nav>\r\n");

            
            #line 73 "..\..\Areas\Admin\Views\User\_Login_Login.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</div>");

        }
    }
}
#pragma warning restore 1591
