#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_Login_Forgot.cshtml")]
    public partial class _Areas_Admin_Views_User__Login_Forgot_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__Login_Forgot_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"forgot-box\"");

WriteLiteral(" class=\"forgot-box widget-box no-border\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"widget-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"widget-main\"");

WriteLiteral(">\r\n            <h4");

WriteLiteral(" class=\"header red lighter bigger\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"ace-icon fa fa-key\"");

WriteLiteral("></i>\r\n                取回密码\r\n            </h4>\r\n\r\n            <div");

WriteLiteral(" class=\"space-6\"");

WriteLiteral("></div>\r\n            <p>\r\n                输入你的邮箱地址\r\n            </p>\r\n\r\n");

            
            #line 14 "..\..\Areas\Admin\Views\User\_Login_Forgot.cshtml"
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\User\_Login_Forgot.cshtml"
             using (Html.BeginForm("ForgetPassword", "User"))
            {

            
            #line default
            #line hidden
WriteLiteral("                <fieldset>\r\n                    <label");

WriteLiteral(" class=\"block clearfix\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"block input-icon input-icon-right\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"email\"");

WriteLiteral(" placeholder=\"Email\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"ace-icon fa fa-envelope\"");

WriteLiteral("></i>\r\n                        </span>\r\n                    </label>\r\n\r\n         " +
"           <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"width-35 pull-right btn btn-sm btn-danger\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"ace-icon fa fa-lightbulb-o\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"bigger-110\"");

WriteLiteral(">发送</span>\r\n                        </button>\r\n                    </div>\r\n      " +
"          </fieldset>\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\User\_Login_Forgot.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div><!-- /.widget-main -->\r\n\r\n        <div");

WriteLiteral(" class=\"toolbar center\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-target=\"#login-box\"");

WriteLiteral(" class=\"back-to-login-link\"");

WriteLiteral(">\r\n                回到登录\r\n                <i");

WriteLiteral(" class=\"ace-icon fa fa-arrow-right\"");

WriteLiteral("></i>\r\n            </a>\r\n        </div>\r\n    </div><!-- /.widget-body -->\r\n</div>" +
"<!-- /.forgot-box -->");

        }
    }
}
#pragma warning restore 1591
