#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 1 "..\..\Areas\Admin\Views\User\Info.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Areas\Admin\Views\User\Info.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Admin\Views\User\Info.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/Info.cshtml")]
    public partial class _Areas_Admin_Views_User_Info_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User_Info_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\User\Info.cshtml"
  
    var fact = EntityFactory.CreateOperate(ViewData.ModelMetadata.ModelType);
    var user = Model as IUser;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\User\Info.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\User\Info.cshtml"
         if (ViewBag.StatusMessage != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"alert alert-success alert-dismissible text-center\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                <strong>");

            
            #line 14 "..\..\Areas\Admin\Views\User\Info.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n            </div>\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\User\Info.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 17 "..\..\Areas\Admin\Views\User\Info.cshtml"
         using (Html.BeginForm("Info", null, new { id = Model[fact.Unique.Name] }))
        {
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\User\Info.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\User\Info.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">名称</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(user.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">密码</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(Html.ForEditor("Password"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">显示名</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(Html.ForEditor("DisplayName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(Html.ForDescription("DisplayName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">邮件</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 43 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(Html.ForEditor("Mail"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">电话</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(Html.ForEditor("Phone"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">代码</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 55 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(Html.ForEditor("Code"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 56 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(Html.ForDescription("Code"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">登录次数</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(user.Logins);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">最后登录</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 70 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(user.LastLogin.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">最后登录IP</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 77 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(user.LastLoginIP);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">配置信息</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 84 "..\..\Areas\Admin\Views\User\Info.cshtml"
               Write(user.Profile);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"clearfix form-actions\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral("></label>\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-save\"");

WriteLiteral(")\"></i><strong>保存</strong></button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(" onclick=\"history.go(-1);\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral("></i><strong>取消</strong></button>\r\n            </div>\r\n");

            
            #line 92 "..\..\Areas\Admin\Views\User\Info.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
