#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Areas\Admin\Views\User\Login.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/Login.cshtml")]
    public partial class _Areas_Admin_Views_User_Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\User\Login.cshtml"
  
    Layout = null;
    //if (ViewBag.Title == null)
    {
        ViewBag.Title = "登录";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh-CN\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n\r\n    <title>");

            
            #line 17 "..\..\Areas\Admin\Views\User\Login.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 17 "..\..\Areas\Admin\Views\User\Login.cshtml"
                       Write(SysConfig.Current.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 471), Tuple.Create("\"", 491)
, Tuple.Create(Tuple.Create("", 478), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 478), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n\r\n    <!-- 文本字体 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 584), Tuple.Create("\"", 626)
, Tuple.Create(Tuple.Create("", 591), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/css/ace-fonts.min.css")
, 591), false)
);

WriteLiteral(" />\r\n    <!-- ace 样式 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 679), Tuple.Create("\"", 715)
, Tuple.Create(Tuple.Create("", 686), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ace/css/ace.min.css")
, 686), false)
);

WriteLiteral(" class=\"ace-main-stylesheet\"");

WriteLiteral(" id=\"main-ace-style\"");

WriteLiteral(@" />

    <!--[if lte IE 9]>
        <link rel=""stylesheet"" href=""~/Content/ace/css/ace-part2.min.css"" class=""ace-main-stylesheet"" />
    <![endif]-->
    <!--[if lte IE 9]>
        <link rel=""stylesheet"" href=""~/Content/ace/css/ace-ie.min.css"" />
    <![endif]-->
    <!-- 最后引入基本样式 -->
    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1085), Tuple.Create("\"", 1133)
, Tuple.Create(Tuple.Create("", 1092), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/bootstrap.min.css")
, 1092), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1165), Tuple.Create("\"", 1216)
, Tuple.Create(Tuple.Create("", 1172), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/font-awesome.min.css")
, 1172), false)
);

WriteLiteral(" />\r\n</head>\r\n<body");

WriteLiteral(" class=\"login-layout light-login\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"main-container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-10 col-sm-offset-1\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"login-container\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"center\"");

WriteLiteral(">\r\n                            <h2>\r\n                                <span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">");

            
            #line 43 "..\..\Areas\Admin\Views\User\Login.cshtml"
                                             Write(SysConfig.Current.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </h2>\r\n                        </div>\r\n     " +
"                   <div");

WriteLiteral(" class=\"space-6\"");

WriteLiteral("></div>\r\n                        <div");

WriteLiteral(" class=\"position-relative\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 48 "..\..\Areas\Admin\Views\User\Login.cshtml"
                       Write(Html.Partial("_Login_Login"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Areas\Admin\Views\User\Login.cshtml"
                       Write(Html.Partial("_Login_Forgot"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 50 "..\..\Areas\Admin\Views\User\Login.cshtml"
                       Write(Html.Partial("_Login_Register"));

            
            #line default
            #line hidden
WriteLiteral(@"
                        </div><!-- /.position-relative -->
                    </div>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.main-content -->
    </div><!-- /.main-container -->
    <!-- JQuery作为一等公民，页面内部随时可能使用 -->
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2293), Tuple.Create("\"", 2331)
, Tuple.Create(Tuple.Create("", 2299), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-2.1.3.min.js")
, 2299), false)
);

WriteLiteral("></script>\r\n    <!-- 最早引入基本脚本 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2378), Tuple.Create("\"", 2423)
, Tuple.Create(Tuple.Create("", 2384), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/js/bootstrap.min.js")
, 2384), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2447), Tuple.Create("\"", 2489)
, Tuple.Create(Tuple.Create("", 2453), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-ui.custom.min.js")
, 2453), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2513), Tuple.Create("\"", 2560)
, Tuple.Create(Tuple.Create("", 2519), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery.ui.touch-punch.min.js")
, 2519), false)
);

WriteLiteral(@"></script>

    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
    <!--[if lte IE 8]>
    <script src=""~/Content/js/html5shiv.min.js""></script>
    <script src=""~/Content/js/respond.min.js""></script>
    <![endif]-->
    <!-- inline scripts related to this page -->
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function ($) {
            $(document).on('click', '.toolbar a[data-target]', function (e) {
                e.preventDefault();
                var target = $(this).data('target');
                $('.widget-box.visible').removeClass('visible');//hide others
                $(target).addClass('visible');//show target
            });
        });
    </script>
</body>
</html>");

        }
    }
}
#pragma warning restore 1591
