#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_Form_Item.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Form_Item.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Cube.Template;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_Item.cshtml")]
    public partial class _Views_Shared__Form_Item_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_Item_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_Form_Item.cshtml"
  
    var pair = Model as Pair;
    var entity = pair.First as IEntity;
    var item = pair.Second as FieldItem;

    var err = 0;
    ModelState st = null;
    if (ViewData.ModelState.TryGetValue(item.Name, out st) && st != null) { err = st.Errors.Count; }

    var des = item.Description.TrimStart(item.DisplayName).TrimStart(",", ".", "，", "。");

    var total = 12;
    var label = 3;
    var span = 4;
    if (err == 0 && des.IsNullOrEmpty())
    {
        span = 0;
    }
    else if (item.Type == typeof(Boolean) || item.Type.IsEnum)
    {
        span += 1;
    }
    var cls_err = err > 0 ? "has-error" : "";

    var input = total - label - span;

    var type = Type.GetTypeCode(item.Type);


            
            #line default
            #line hidden
WriteLiteral("\r\n<label");

WriteLiteral(" class=\"control-label col-sm-3\"");

WriteLiteral(">");

            
            #line 34 "..\..\Views\Shared\_Form_Item.cshtml"
                                 Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 889), Tuple.Create("\"", 914)
, Tuple.Create(Tuple.Create("", 897), Tuple.Create("col-sm-5", 897), true)
            
            #line 36 "..\..\Views\Shared\_Form_Item.cshtml"
, Tuple.Create(Tuple.Create(" ", 905), Tuple.Create<System.Object, System.Int32>(cls_err
            
            #line default
            #line hidden
, 906), false)
);

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Views\Shared\_Form_Item.cshtml"
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Shared\_Form_Item.cshtml"
     if (type == TypeCode.DateTime)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"input-group date\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\r\n            <input");

WriteAttribute("id", Tuple.Create(" id=\"", 1103), Tuple.Create("\"", 1113)
            
            #line 41 "..\..\Views\Shared\_Form_Item.cshtml"
, Tuple.Create(Tuple.Create("", 1108), Tuple.Create<System.Object, System.Int32>(item
            
            #line default
            #line hidden
, 1108), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1114), Tuple.Create("\"", 1126)
            
            #line 41 "..\..\Views\Shared\_Form_Item.cshtml"
, Tuple.Create(Tuple.Create("", 1121), Tuple.Create<System.Object, System.Int32>(item
            
            #line default
            #line hidden
, 1121), false)
);

WriteLiteral(" type=\"text\"");

WriteLiteral(" dateformat=\"yyyy-mm-dd hh:ii:ss\"");

WriteLiteral(" class=\"form-control form_datetime\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1207), Tuple.Create("\"", 1241)
            
            #line 41 "..\..\Views\Shared\_Form_Item.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 1215), Tuple.Create<System.Object, System.Int32>(entity[item].ToDateTime()
            
            #line default
            #line hidden
, 1215), false)
);

WriteLiteral(">\r\n        </div>\r\n");

            
            #line 43 "..\..\Views\Shared\_Form_Item.cshtml"
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Shared\_Form_Item.cshtml"
   Write(Html.ForEditor(item, entity));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Shared\_Form_Item.cshtml"
                                     
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

            
            #line 50 "..\..\Views\Shared\_Form_Item.cshtml"
 if (err > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <span");

WriteLiteral(" class=\"col-sm-4 alert alert-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 53 "..\..\Views\Shared\_Form_Item.cshtml"
   Write(Html.ValidationMessage(item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </span>\r\n");

            
            #line 55 "..\..\Views\Shared\_Form_Item.cshtml"
}
else if (!des.IsNullOrEmpty())
{

            
            #line default
            #line hidden
WriteLiteral("    <span");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">");

            
            #line 58 "..\..\Views\Shared\_Form_Item.cshtml"
                      Write(Html.ForDescription(item));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 59 "..\..\Views\Shared\_Form_Item.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
