#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 1 "..\..\Views\Shared\Form.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 3 "..\..\Views\Shared\Form.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Cube.Template;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Views\Shared\Form.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Form.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Form.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Form.cshtml")]
    public partial class _Views_Shared_Form_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Shared\Form.cshtml"
  
    Layout = NewLife.Cube.Setting.Current.Layout;

    var fact = ViewBag.Factory as IEntityOperate;
    var fields = ViewBag.Fields as List<FieldItem>;
    var entity = Model as IEntity;
    var isNew = entity.IsNullKey;

    var rv = entity.GetRouteKey();
    IDictionary<string, object> dic = new Dictionary<string, object>();
    dic.Add("class", "form-horizontal");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(" style=\"padding:0px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ibox-title\"");

WriteLiteral(">\r\n            <h5>");

            
            #line 22 "..\..\Views\Shared\Form.cshtml"
           Write(ViewBag.HeaderContent);

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Shared\Form.cshtml"
       Write(Html.Partial("_Form_Header", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 26 "..\..\Views\Shared\Form.cshtml"
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\Form.cshtml"
             using (Html.BeginForm((isNew ? "Add" : "Edit"), null, rv, FormMethod.Post, dic))
            {
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\Form.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\Form.cshtml"
                                        
                
                foreach (var item in fields)
                {
                    if (!item.IsIdentity)
                    {
                        
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\Form.cshtml"
                   Write(Html.Partial("_Form_Group", new Pair(Model, item)));

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\Form.cshtml"
                                                                           
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"hr-line-dashed\"");

WriteLiteral("></div>\r\n");

            
            #line 38 "..\..\Views\Shared\Form.cshtml"
                
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Shared\Form.cshtml"
           Write(Html.Partial("_Form_Action", entity));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Shared\Form.cshtml"
                                                     
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n");

DefineSection("css", () => {

WriteLiteral("\r\n\r\n");

});

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n");

});

        }
    }
}
#pragma warning restore 1591
