#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Sys/SysConfig.cshtml")]
    public partial class _Areas_Admin_Views_Sys_SysConfig_cshtml : System.Web.Mvc.WebViewPage<NewLife.Common.SysConfig>
    {
        public _Areas_Admin_Views_Sys_SysConfig_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
  
    Layout = "~/Views/Shared/_Ace_Layout.cshtml";
    ViewBag.Title = "系统配置";

    var isNew = false;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
         using (Html.BeginForm())
        {
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
       Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
                                         


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 19 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 20 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.Version, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.Version));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.Version));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.DisplayName, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.Company, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.Company));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.Company));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 47 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.Address));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 48 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.Address));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 52 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.Tel, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 55 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 59 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.Fax, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.Fax));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 62 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.Fax));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

            
            #line 65 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 67 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.EMail, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 69 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.EMail));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 70 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.EMail));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 74 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.IsEnable, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 76 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.IsEnable));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 77 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.IsEnable));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 81 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
           Write(Html.LabelFor(model => model.InstallTime, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"input-group col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 83 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ForEditor(model => model.InstallTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 84 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
               Write(Html.ValidationMessageFor(model => model.InstallTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-actions\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral("></label>\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 4165), Tuple.Create("\"", 4219)
, Tuple.Create(Tuple.Create("", 4173), Tuple.Create("glyphicon", 4173), true)
, Tuple.Create(Tuple.Create(" ", 4182), Tuple.Create("glyphicon-", 4183), true)
            
            #line 89 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
             , Tuple.Create(Tuple.Create("", 4193), Tuple.Create<System.Object, System.Int32>(isNew ? "plus" : "save"
            
            #line default
            #line hidden
, 4193), false)
);

WriteLiteral("></i><strong>");

            
            #line 89 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
                                                                                                                                Write(isNew ? "新增" : "保存");

            
            #line default
            #line hidden
WriteLiteral("</strong></button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" onclick=\"history.go(-1);\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral("></i><strong>取消</strong></button>\r\n            </div>\r\n");

            
            #line 92 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 97 "..\..\Areas\Admin\Views\Sys\SysConfig.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
