#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Cube.Template;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 1 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_Form_Action.cshtml")]
    public partial class _Areas_Admin_Views_User__Form_Action_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__Form_Action_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
  
    var entity = Model as IEntity;
    var isNew = entity.IsNullKey;
    var user = ViewBag.User as IUser ?? User.Identity as IUser;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
 if (user.Has(PermissionFlags.Insert, PermissionFlags.Update))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-5 col-sm-offset-3\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 381), Tuple.Create("\"", 435)
, Tuple.Create(Tuple.Create("", 389), Tuple.Create("glyphicon", 389), true)
, Tuple.Create(Tuple.Create(" ", 398), Tuple.Create("glyphicon-", 399), true)
            
            #line 11 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
                 , Tuple.Create(Tuple.Create("", 409), Tuple.Create<System.Object, System.Int32>(isNew ? "plus" : "save"
            
            #line default
            #line hidden
, 409), false)
);

WriteLiteral("></i><strong>");

            
            #line 11 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
                                                                                                                                   Write(isNew ? "新增" : "保存");

            
            #line default
            #line hidden
WriteLiteral("</strong></button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(" onclick=\"history.go(-1);\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral("></i><strong>取消</strong></button>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 667), Tuple.Create("\"", 714)
, Tuple.Create(Tuple.Create("", 674), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/User/ClearPassword/")
, 674), false)
            
            #line 13 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
, Tuple.Create(Tuple.Create("", 701), Tuple.Create<System.Object, System.Int32>(entity["ID"]
            
            #line default
            #line hidden
, 701), false)
);

WriteLiteral(" class=\" btn btn-info btn-sm\"");

WriteLiteral(" title=\"数据库为空密码时，任何密码均可登录\"");

WriteLiteral(">清空密码</a>\r\n        </div>\r\n    </div>\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\User\_Form_Action.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
